engineStrict: true
minimumReleaseAge: 2880
saveExact: true
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - apps/*
  - packages/*

catalog:
  '@tailwindcss/vite': 4.1.18
  '@vitejs/plugin-basic-ssl': 2.1.4
  eslint-plugin-format: 1.4.0
  tailwindcss: 4.1.18
