packages:
  - apps/*
  - packages/*

catalog:
  '@tailwindcss/vite': 4.1.18
  '@vitejs/plugin-basic-ssl': 2.1.3
  eslint-plugin-format: 1.3.1
  tailwindcss: 4.1.18

engineStrict: true

minimumReleaseAge: 2880

saveExact: true
