allowBuilds:
  esbuild: true
  sharp: set this to true or false
  simple-git-hooks: set this to true or false

engineStrict: true

saveExact: true

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - vite
packages:
  - apps/*
  - packages/*
catalog:
  '@tailwindcss/vite': 4.3.3
  '@vitejs/plugin-basic-ssl': 2.3.0
  eslint-plugin-format: 2.0.1
  eslint-plugin-tailwindcss: 4.2.0
  tailwindcss: 4.3.3
onlyBuiltDependencies:
  - esbuild
  - sharp
