engineStrict: true
saveExact: true
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - vite

packages:
  - apps/*
  - packages/*
catalog:
  '@tailwindcss/vite': 4.2.1
  '@vitejs/plugin-basic-ssl': 2.1.4
  eslint-plugin-format: 2.0.0
  tailwindcss: 4.2.1
