packages:
  - apps/*
  - packages/*

catalog:
  '@tailwindcss/vite': 4.1.18
  '@vitejs/plugin-basic-ssl': 2.1.0
  eslint-plugin-format: 1.1.0
  tailwindcss: 4.1.18

minimumReleaseAge: 2880
engineStrict: true
saveExact: true
