packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: set this to true or false
  sharp: set this to true or false
  simple-git-hooks: set this to true or false

catalog:
  '@tailwindcss/vite': 4.2.4
  '@vitejs/plugin-basic-ssl': 2.3.0
  eslint-plugin-format: 2.0.1
  tailwindcss: 4.2.4
engineStrict: true

onlyBuiltDependencies:
  - esbuild
  - sharp

saveExact: true

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - vite
